// Mock timetable data with comprehensive test scenarios

import type { TimetableEntry, TimetableModification, ChangeProposal } from "./types"

// Subject colors for visual consistency
export const SUBJECT_COLORS: Record<string, string> = {
  Mathématiques: "bg-blue-100 border-blue-300 text-blue-900",
  Français: "bg-purple-100 border-purple-300 text-purple-900",
  "Histoire-Géo": "bg-amber-100 border-amber-300 text-amber-900",
  Anglais: "bg-green-100 border-green-300 text-green-900",
  "Physique-Chimie": "bg-red-100 border-red-300 text-red-900",
  Philosophie: "bg-indigo-100 border-indigo-300 text-indigo-900",
  SVT: "bg-emerald-100 border-emerald-300 text-emerald-900",
  EPS: "bg-orange-100 border-orange-300 text-orange-900",
  Espagnol: "bg-pink-100 border-pink-300 text-pink-900",
  Informatique: "bg-cyan-100 border-cyan-300 text-cyan-900",
}

// Mock teachers
export const MOCK_TEACHERS = [
  { email: "prof@example.com", name: "M. Dupont", subject: "Mathématiques" },
  { email: "mme.martin@example.com", name: "Mme Martin", subject: "Français" },
  { email: "m.bernard@example.com", name: "M. Bernard", subject: "Histoire-Géo" },
  { email: "mrs.smith@example.com", name: "Mrs. Smith", subject: "Anglais" },
  { email: "mme.rousseau@example.com", name: "Mme Rousseau", subject: "Physique-Chimie" },
  { email: "m.lefebvre@example.com", name: "M. Lefebvre", subject: "Philosophie" },
]

// Mock classes
export const MOCK_CLASSES = [
  { id: "term-a", name: "Terminale A" },
  { id: "term-b", name: "Terminale B" },
  { id: "prem-a", name: "Première A" },
  { id: "prem-b", name: "Première B" },
  { id: "sec-a", name: "Seconde A" },
  { id: "sec-b", name: "Seconde B" },
]

// Mock timetable entries with various scenarios
export const MOCK_TIMETABLE_ENTRIES: TimetableEntry[] = [
  // M. Dupont (prof@example.com) - Mathématiques
  {
    id: "entry-1",
    courseId: "course-math-1",
    subject: "Mathématiques",
    teacher: "M. Dupont",
    teacherEmail: "prof@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Salle 201",
    day: "Lundi",
    startHour: "8h",
    endHour: "10h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Mathématiques"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-15"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },
  {
    id: "entry-2",
    courseId: "course-math-2",
    subject: "Mathématiques",
    teacher: "M. Dupont",
    teacherEmail: "prof@example.com",
    class: "Première A",
    classId: "prem-a",
    room: "Salle 201",
    day: "Lundi",
    startHour: "10h",
    endHour: "12h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Mathématiques"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },
  {
    id: "entry-3",
    courseId: "course-math-3",
    subject: "Mathématiques",
    teacher: "M. Dupont",
    teacherEmail: "prof@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Salle 201",
    day: "Mercredi",
    startHour: "14h",
    endHour: "16h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Mathématiques"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },

  // Mme Martin - Français
  {
    id: "entry-4",
    courseId: "course-fr-1",
    subject: "Français",
    teacher: "Mme Martin",
    teacherEmail: "mme.martin@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Salle 105",
    day: "Mardi",
    startHour: "10h",
    endHour: "12h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Français"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },
  {
    id: "entry-5",
    courseId: "course-fr-2",
    subject: "Français",
    teacher: "Mme Martin",
    teacherEmail: "mme.martin@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Salle 105",
    day: "Jeudi",
    startHour: "8h",
    endHour: "10h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Français"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },

  // M. Bernard - Histoire-Géo
  {
    id: "entry-6",
    courseId: "course-hg-1",
    subject: "Histoire-Géo",
    teacher: "M. Bernard",
    teacherEmail: "m.bernard@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Salle 302",
    day: "Lundi",
    startHour: "14h",
    endHour: "16h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Histoire-Géo"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },
  {
    id: "entry-7",
    courseId: "course-hg-2",
    subject: "Histoire-Géo",
    teacher: "M. Bernard",
    teacherEmail: "m.bernard@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Salle 302",
    day: "Vendredi",
    startHour: "10h",
    endHour: "12h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Histoire-Géo"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },

  // Mrs. Smith - Anglais
  {
    id: "entry-8",
    courseId: "course-en-1",
    subject: "Anglais",
    teacher: "Mrs. Smith",
    teacherEmail: "mrs.smith@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Salle 108",
    day: "Mercredi",
    startHour: "8h",
    endHour: "10h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Anglais"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },
  {
    id: "entry-9",
    courseId: "course-en-2",
    subject: "Anglais",
    teacher: "Mrs. Smith",
    teacherEmail: "mrs.smith@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Salle 108",
    day: "Vendredi",
    startHour: "14h",
    endHour: "16h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Anglais"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },

  // Mme Rousseau - Physique-Chimie
  {
    id: "entry-10",
    courseId: "course-pc-1",
    subject: "Physique-Chimie",
    teacher: "Mme Rousseau",
    teacherEmail: "mme.rousseau@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Labo A",
    day: "Mardi",
    startHour: "14h",
    endHour: "16h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Physique-Chimie"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },
  {
    id: "entry-11",
    courseId: "course-pc-2",
    subject: "Physique-Chimie",
    teacher: "Mme Rousseau",
    teacherEmail: "mme.rousseau@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Labo A",
    day: "Jeudi",
    startHour: "14h",
    endHour: "16h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Physique-Chimie"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },

  // M. Lefebvre - Philosophie (Week A only)
  {
    id: "entry-12",
    courseId: "course-philo-1",
    subject: "Philosophie",
    teacher: "M. Lefebvre",
    teacherEmail: "m.lefebvre@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Salle 204",
    day: "Lundi",
    startHour: "10h",
    endHour: "12h",
    weekType: "A",
    status: "confirmed",
    color: SUBJECT_COLORS["Philosophie"],
    notes: "Uniquement semaine A",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },

  // SVT (Week B only) - Creates a conflict scenario
  {
    id: "entry-13",
    courseId: "course-svt-1",
    subject: "SVT",
    teacher: "M. Durand",
    teacherEmail: "m.durand@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Labo B",
    day: "Jeudi",
    startHour: "10h",
    endHour: "12h",
    weekType: "B",
    status: "confirmed",
    color: SUBJECT_COLORS["SVT"],
    notes: "Uniquement semaine B",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },

  // EPS
  {
    id: "entry-14",
    courseId: "course-eps-1",
    subject: "EPS",
    teacher: "M. Moreau",
    teacherEmail: "m.moreau@example.com",
    class: "Terminale A",
    classId: "term-a",
    room: "Gymnase",
    day: "Vendredi",
    startHour: "16h",
    endHour: "17h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["EPS"],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },

  // Conflict scenario: Same room at same time (for testing)
  {
    id: "entry-conflict-1",
    courseId: "course-conflict-1",
    subject: "Informatique",
    teacher: "M. Dupont",
    teacherEmail: "prof@example.com",
    class: "Première B",
    classId: "prem-b",
    room: "Salle 201", // Same room as entry-2
    day: "Lundi",
    startHour: "10h",
    endHour: "11h",
    weekType: "both",
    status: "confirmed",
    color: SUBJECT_COLORS["Informatique"],
    notes: "CONFLIT: Même salle que Mathématiques Première A",
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
    createdBy: "responsable1@test.com",
    updatedBy: "responsable1@test.com",
  },
]

// Mock modification history
export const MOCK_MODIFICATIONS: TimetableModification[] = [
  {
    id: "mod-1",
    entryId: "entry-1",
    action: "modified",
    user: "Responsable 1",
    userRole: "responsable",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    details: "Changement de salle: 203 → 201",
    isLate: false,
    oldValues: { room: "Salle 203" },
    newValues: { room: "Salle 201" },
  },
  {
    id: "mod-2",
    entryId: "entry-6",
    action: "moved",
    user: "Responsable 2",
    userRole: "responsable",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    details: "Déplacé de Mardi 14h à Lundi 14h",
    isLate: true,
    oldValues: { day: "Mardi", startHour: "14h" },
    newValues: { day: "Lundi", startHour: "14h" },
  },
  {
    id: "mod-3",
    entryId: "entry-8",
    action: "created",
    user: "Responsable 1",
    userRole: "responsable",
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    details: "Nouveau cours d'Anglais créé",
    isLate: false,
  },
]

// Mock change proposals from teachers
export const MOCK_CHANGE_PROPOSALS: ChangeProposal[] = [
  {
    id: "prop-1",
    entryId: "entry-1",
    proposedBy: "M. Dupont",
    proposedByEmail: "prof@example.com",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    reason: "Salle 201 non disponible - équipement en panne",
    proposedChanges: {
      room: "Salle 203",
    },
    status: "pending",
  },
  {
    id: "prop-2",
    entryId: "entry-4",
    proposedBy: "Mme Martin",
    proposedByEmail: "mme.martin@example.com",
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000),
    reason: "Demande de changement d'horaire pour examen",
    proposedChanges: {
      startHour: "14h",
      endHour: "16h",
    },
    status: "approved",
    reviewedBy: "Responsable 1",
    reviewedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
]
