import type { Devoir, Course, Class } from "./types"

// Mock courses
export const MOCK_COURSES: Course[] = [
  { id: "1", name: "Mathématiques", teacherEmail: "prof@example.com" },
  { id: "2", name: "Français", teacherEmail: "prof@example.com" },
  { id: "3", name: "Physique-Chimie", teacherEmail: "prof@example.com" },
  { id: "4", name: "Histoire-Géographie", teacherEmail: "prof2@example.com" },
  { id: "5", name: "Anglais", teacherEmail: "prof2@example.com" },
]

// Mock classes
export const MOCK_CLASSES: Class[] = [
  { id: "1", name: "Terminale A" },
  { id: "2", name: "Première B" },
  { id: "3", name: "Seconde C" },
]

// Mock devoirs with various statuses and dates
export const MOCK_DEVOIRS: Devoir[] = [
  {
    id: "1",
    title: "Exercices chapitre 5",
    description: "Compléter les exercices 1 à 15 page 87",
    courseId: "1",
    courseName: "Mathématiques",
    classIds: ["1"],
    classNames: ["Terminale A"],
    authorEmail: "prof@example.com",
    authorName: "Professeur Demo",
    createdAt: "2025-10-10T10:00:00",
    dueDate: "2025-10-18",
    status: "published",
    priority: "high",
    history: [
      {
        by: "Professeur Demo",
        role: "teacher",
        when: "2025-10-10T10:00:00",
        changes: "Devoir créé",
      },
      {
        by: "Professeur Demo",
        role: "teacher",
        when: "2025-10-10T10:05:00",
        changes: "Statut changé: draft → published",
      },
    ],
  },
  {
    id: "2",
    title: "Dissertation sur le romantisme",
    description: "Rédiger une dissertation de 3 pages sur le mouvement romantique",
    courseId: "2",
    courseName: "Français",
    classIds: ["1"],
    classNames: ["Terminale A"],
    authorEmail: "prof@example.com",
    authorName: "Professeur Demo",
    createdAt: "2025-10-08T14:00:00",
    dueDate: "2025-10-20",
    status: "published",
    resourceUrl: "https://example.com/romantisme-guide.pdf",
    priority: "high",
    history: [
      {
        by: "Professeur Demo",
        role: "teacher",
        when: "2025-10-08T14:00:00",
        changes: "Devoir créé et publié",
      },
    ],
  },
  {
    id: "3",
    title: "TP Chimie organique",
    description: "Compte-rendu du TP sur les réactions d'estérification",
    courseId: "3",
    courseName: "Physique-Chimie",
    classIds: ["1", "2"],
    classNames: ["Terminale A", "Première B"],
    authorEmail: "prof@example.com",
    authorName: "Professeur Demo",
    createdAt: "2025-10-12T09:00:00",
    dueDate: "2025-10-21",
    status: "published",
    priority: "medium",
    history: [
      {
        by: "Professeur Demo",
        role: "teacher",
        when: "2025-10-12T09:00:00",
        changes: "Devoir créé et publié",
      },
    ],
  },
  {
    id: "4",
    title: "Brouillon - Révisions algèbre",
    description: "Exercices de révision sur l'algèbre linéaire",
    courseId: "1",
    courseName: "Mathématiques",
    classIds: ["2"],
    classNames: ["Première B"],
    authorEmail: "prof@example.com",
    authorName: "Professeur Demo",
    createdAt: "2025-10-14T16:00:00",
    dueDate: "2025-10-25",
    status: "draft",
    priority: "medium",
    history: [
      {
        by: "Professeur Demo",
        role: "teacher",
        when: "2025-10-14T16:00:00",
        changes: "Devoir créé (brouillon)",
      },
    ],
  },
  {
    id: "5",
    title: "Exposé sur la Seconde Guerre mondiale",
    description: "Préparer un exposé de 10 minutes sur un aspect de la Seconde Guerre mondiale",
    courseId: "4",
    courseName: "Histoire-Géographie",
    classIds: ["1"],
    classNames: ["Terminale A"],
    authorEmail: "prof2@example.com",
    authorName: "Professeur 2",
    createdAt: "2025-10-05T11:00:00",
    dueDate: "2025-10-23",
    status: "published",
    priority: "medium",
    history: [
      {
        by: "Professeur 2",
        role: "teacher",
        when: "2025-10-05T11:00:00",
        changes: "Devoir créé et publié",
      },
    ],
  },
  {
    id: "6",
    title: "Exercices de grammaire",
    description: "Compléter les exercices du workbook pages 45-48",
    courseId: "5",
    courseName: "Anglais",
    classIds: ["1", "2"],
    classNames: ["Terminale A", "Première B"],
    authorEmail: "prof2@example.com",
    authorName: "Professeur 2",
    createdAt: "2025-10-13T10:00:00",
    dueDate: "2025-10-25",
    status: "published",
    priority: "low",
    history: [
      {
        by: "Professeur 2",
        role: "teacher",
        when: "2025-10-13T10:00:00",
        changes: "Devoir créé et publié",
      },
    ],
  },
  {
    id: "7",
    title: "Devoir passé - Analyse de texte",
    description: "Analyse du texte de Victor Hugo",
    courseId: "2",
    courseName: "Français",
    classIds: ["1"],
    classNames: ["Terminale A"],
    authorEmail: "prof@example.com",
    authorName: "Professeur Demo",
    createdAt: "2025-09-20T10:00:00",
    dueDate: "2025-10-05",
    status: "published",
    priority: "high",
    history: [
      {
        by: "Professeur Demo",
        role: "teacher",
        when: "2025-09-20T10:00:00",
        changes: "Devoir créé et publié",
      },
    ],
  },
  {
    id: "8",
    title: "Lecture et fiche de lecture",
    description: "Lire le chapitre 3 et rédiger une fiche de lecture",
    courseId: "2",
    courseName: "Français",
    classIds: ["2"],
    classNames: ["Première B"],
    authorEmail: "prof@example.com",
    authorName: "Professeur Demo",
    createdAt: "2025-10-11T15:00:00",
    dueDate: "2025-10-27",
    status: "published",
    priority: "low",
    history: [
      {
        by: "Professeur Demo",
        role: "teacher",
        when: "2025-10-11T15:00:00",
        changes: "Devoir créé et publié",
      },
    ],
  },
]
